### ISSUE TITLE
camera_projection

### ISSUE THREAD

**Issue by Jillian-Wang** [AutoCheckout-CMU/AutoCheckout#4]
hi, thank you for your outstanding work.

I want to visually check the joint postion on image, using your code of camera_projection() and the joints from json file, in my understanding, the result of camera_projection() is the joint in pixel coordinate, which can be shown directly on image, but when i show the result of camera_projection() on image found that the joint position cann't match the image, the joints are far from the actual position on image and the joints are grouped together.

Do I need to do extra process before calling camera_projection()?  Thank you very much

**Comment by MengmengZHANG** [comment]
Hi,

I believe this method is just a prototype and never used by the main pipeline.
If I remember well, we have tried to use the 3D to 2D projection following the guide from: https://en.wikipedia.org/wiki/Camera_resectioning, but we have never succeeded to do it.
We have similar problems as you.

Best,

**Comment by Jillian-Wang** [comment]
@MengmengZHANG

Thank you very much for your reply.
